### ISSUE TITLE
Update Henshin to 1.6.0

### ISSUE THREAD

**Issue by lursyy** [ContextMapper/henshin-interpreter#1]
I am using this as a gradle import for my thesis.
Henshin 1.6.0 was [released](https://www.eclipse.org/lists/henshin-user/msg00194.html) "recently". Could you incorporate this latest Henshin update into the maven repo?

(I would submit a PR, but have no idea how to accomplish this -- is it enough to just replace the `henshin` folder?)

**Comment by stefan-ka** [comment]
Hi @lursyy 

Sorry for the late response!

Yes, of course. I published the 1.6.0 to the Maven central right now. It's already available... (I guess you are aware that this lib only contains the interpreter and not the rest of the Henshin project)

I assume this issue can be closed.

Best regards,
Stefan

**Comment by lursyy** [comment]
Thanks!
